### ISSUE TITLE
关于协议栈的一些疑问

### ISSUE THREAD

**Issue by scarleast** [actg/JN5169-for-xiaomi-wireless-switch#1]
我有一个疑问，这款芯片是自带的有固件还是和TI的CC2530之类的一样，也是用类似Z-STACK这种厂商提供的协议栈做二次的开发？

**Comment by actg** [comment]
不是自带的固件，固件可以通过ISP写入，自带了bootloader倒是真的，应该是存储在ROM区的bootloader，和TI一样，核心功能密封成库，其他暴露出来给上层做开发调用

**Comment by scarleast** [comment]
这玩意儿就是资料太少了，不知道绿米为什么选择这个芯片~

**Comment by actg** [comment]
NXP的zigbee比较冷门，用的人比较少，故有门槛，不过原理都是一样的，整个协议栈代码也很简单。
